
# defaults:
# label = name
# id type = id
# type = string

types:
  - name: language
    fields:
      - name: id
        minLength: 2
        maxLength: 2
      - name: label
        required: true

  - name: menu
    fields:
      - name: id
      - name: items
        type: array
        arrayOf: menuItem
#      - name: obj
#        type: menuItem
#      - name: label
#      - name: component
#      - name: segment
#      - name: page
#        type: link
#      - name: pub
#        type: boolean
#      - name: order
#        type: number

  - name: page
    folders: true
    fields:
      - name: id
      - name: lang
        label: Language
        descr: Page language
        required: true
        minLength: 2
        maxLength: 2
      - name: metaTitle
        maxLength: 40
      - name: metaDescription
        maxLength: 140
      - name: date1
        type: date
      - name: pub
        label: Published
        descr: If article is published
        type: boolean
      - name: content
        type: markdown
      - name: num1
        type: number

  - name: menuItem
    label: Menu item
    fields:
      - name: label
#      - name: component
#      - name: segment
      - name: url
#      - name: page
#        type: link
      - name: pub
        type: boolean

  - name: objtype2
    fields:
      - name: field1
      - name: field2

collections:
  - name: languages
    icon: language
    folders: false
    type: language

  - name: menus
    folders: true
    type: menu

  - name: pages
    folders: true
    type: page
